spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.pool.max-total=20
spring.redis.pool.max-idle=10
spring.redis.pool.min-idle=2
app.api-key=${API_KEY}
app.url.ttl-days=30
server.port=8080
logging.level.urlshortener.app=INFO
logging.file.name=logs/app-prod.log
